CREATE DATABASE IF NOT EXISTS alma_vida CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE alma_vida;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  document_type VARCHAR(10) NOT NULL,
  address VARCHAR(180) NOT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  mobile VARCHAR(30) NOT NULL,
  birth_date DATE NOT NULL,
  age TINYINT UNSIGNED NOT NULL,
  eps VARCHAR(80) NOT NULL,
  additional_contact VARCHAR(120) DEFAULT NULL,
  kinship VARCHAR(80) DEFAULT NULL,
  exam_type VARCHAR(120) NOT NULL,
  company VARCHAR(120) NOT NULL,
  exam_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (name, email, password)
VALUES ('Administrador', 'admin@almavida.com', '$2y$12$6fFCchd/wabFoADQHgwqkOZlTlR1aR7Uh8nqXlin1i52NYfjtchu2');
